Repository roberto-butti/some-drops-of-javascript, pull requests merged in 2023-10, with the labels that each got.

#8 Add Documentation for `typeof` operator
  examples/03-01_op-typeof.mjs
  list-of-functions.md
  src/content/docs/03-var/01_op-typeof.md
Labels: hacktoberfest, hacktoberfest-accepted

#9 adding new item in sidebar for chapter 3
  astro.config.mjs
Labels: hacktoberfest, hacktoberfest-accepted

#14 adds map()
  examples/02-11_array-map.mjs
  list-of-functions.md
  src/content/docs/02-array/11_array-map.md
Labels: hacktoberfest, hacktoberfest-accepted

#15 Added property description for path.sep #7
  examples/03-02_path-sep.mjs
  list-of-functions.md
  src/content/docs/03-var/02_path-sep.md
Labels: hacktoberfest, hacktoberfest-accepted

#10 :pencil: adds 05_getting-all-the-object-properties-attributes
  src/content/docs/03-var/05_getting-all-the-object-properties-attributes.md
  src/content/docs/03-var/06_object-values.md
Labels: hacktoberfest

#11 :pencil: adds 06_object-values
  src/content/docs/03-var/06_object-values.md
Labels: hacktoberfest

#20 Adding empty chapter for functions and strings
  astro.config.mjs
  src/content/docs/04-functions/00_functions.md
  src/content/docs/05-string/00_string.md
Labels: hacktoberfest, hacktoberfest-accepted

#23 Update 07_array-fill.md & 02-07_array-fill.mjs
  examples/02-07_array-fill.mjs
  src/content/docs/02-array/07_array-fill.md
Labels: hacktoberfest, hacktoberfest-accepted

#24 Add new functions for padding strings
  examples/05-02_str-padding.mjs
  src/content/docs/05-string/02_str-padding.md
Labels: hacktoberfest, hacktoberfest-accepted

#25 Added property description for reduce() #5
  examples/02-12_array-reduce.mjs
  list-of-functions.md
  src/content/docs/02-array/12_array-reduce.md
Labels: hacktoberfest, hacktoberfest-accepted

#27 removing bug
  src/content/docs/02-array/02_array-includes.md
Labels: hacktoberfest, hacktoberfest-accepted

#31 Added property description for os.EOL #28
  examples/03-03_os-eol.mjs
  list-of-functions.md
  src/content/docs/03-var/03_os-eol.md
Labels: hacktoberfest, hacktoberfest-accepted

#35 Changed font to Montserrat
  package-lock.json
  src/styles/custom.css
Labels: hacktoberfest, hacktoberfest-accepted

#37 New Function : getOwnPropertyNames()
  src/content/docs/03-var/04_object-getOwnPropertyNames.md
Labels: hacktoberfest-accepted

#36 New function: string concat()
  examples/05-01_str-concat.mjs
  src/content/docs/05-string/01_str-concat.md
Labels: hacktoberfest, hacktoberfest-accepted
